In [30]:
a = np.arange(24).reshape(4,2,3)
b =a[[0]]
print(a)
print(b)
print(b.ndim)
print("")
print("==============================")
c = a[[0],:,[1]]
print(c)  
print(c.ndim)
print("")

print("==============================")
e = a[[0,1], :, [0,2]]
print(e.ndim)
print(e)
print("")
print("==============================")

f = a[[[0], [1]], :, [0, 2]]
print(f)
print(f.ndim)


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
[[[0 1 2]
  [3 4 5]]]
3

[[1 4]]
2

2
[[ 0  3]
 [ 8 11]]

[[[ 0  3]
  [ 2  5]]

 [[ 6  9]
  [ 8 11]]]
3


In [4]:
import numpy as np

# 1. 시드 고정 및 가상의 학생 성적 데이터셋 생성 (학생 5명, 과목 3개)
np.random.seed(42)
scores = np.random.randint(40, 101, size=(5, 3))

print("1. 원본 성적 데이터셋 (5명 x 3과목):")
print(scores)

# 2. 각 과목별 평균 및 표준편차 구하기 (axis=0: 세로/열 방향 연산)
subject_mean = np.mean(scores, axis=0)
subject_std = np.std(scores, axis=0)

print("\n2. 과목별 평균:")
print(subject_mean)

print("\n3. 과목별 표준편차:")
print(np.round(subject_std, 2))

# 3. 각 학생별 평균 구하기 (axis=1: 가로/행 방향 연산)
student_mean = np.mean(scores, axis=1)

print("\n4. 학생별 평균 점수:")
print(np.round(student_mean, 2))

# 4. 낙제점 수정하기 (60점 미만인 점수를 60점으로 일괄 수정)
# np.where(조건, 참일 때 값, 거짓일 때 값) 활용
fixed_scores = np.where(scores < 60, 60, scores)

print("\n5. 낙제점(60점 미만) 수정 후 데이터셋:")
print(fixed_scores)

1. 원본 성적 데이터셋 (5명 x 3과목):
[[ 78  91  68]
 [ 54  82  47]
 [100  60  78]
 [ 97  58  62]
 [ 50  50  63]]

2. 과목별 평균:
[75.8 68.2 63.6]

3. 과목별 표준편차:
[20.88 15.57 10.05]

4. 학생별 평균 점수:
[79.   61.   79.33 72.33 54.33]

5. 낙제점(60점 미만) 수정 후 데이터셋:
[[ 78  91  68]
 [ 60  82  60]
 [100  60  78]
 [ 97  60  62]
 [ 60  60  63]]


In [5]:
import numpy as np

# 1. 가상의 RGB 이미지 픽셀 데이터 생성 (높이 4 x 너비 4 x 채널 3)
np.random.seed(100)
image_rgb = np.random.randint(0, 256, size=(4, 4, 3), dtype=np.uint8)

print("1. 원본 RGB 이미지 Shape:")
print(image_rgb.shape)

# 2. RGB 흑백 전환 (Grayscale Conversion)
# ITU-R BT.601 표준 공식: Y = 0.299*R + 0.587*G + 0.114*B
# 채널 축(axis 2)에 가중치를 내적(Dot Product)하거나 브로드캐스팅하여 계산함
weights = np.array([0.299, 0.587, 0.114])
image_gray = np.dot(image_rgb, weights).astype(np.uint8)

print("\n2. 흑백 전환 후 이미지 Shape:")
print(image_gray.shape)  # (4, 4)로 차원 축소됨

print("\n3. 흑백 이미지 픽셀 값:")
print(image_gray)

# 3. 이미지 크기 조절 (Downsampling / Resizing)
# 슬라이싱([::2, ::2])을 이용하여 가로/세로 픽셀을 2칸씩 스킵함으로써 크기를 1/2로 줄임
image_resized = image_gray[::2, ::2]

print("\n4. 크기 조절(2x2로 축소) 후 이미지 Shape:")
print(image_resized.shape)

print("\n5. 최종 축소된 이미지 픽셀 값:")
print(image_resized)

1. 원본 RGB 이미지 Shape:
(4, 4, 3)

2. 흑백 전환 후 이미지 Shape:
(4, 4)

3. 흑백 이미지 픽셀 값:
[[ 93  80 170  63]
 [175  87 124 128]
 [ 97 173  36  50]
 [ 89  73  33 139]]

4. 크기 조절(2x2로 축소) 후 이미지 Shape:
(2, 2)

5. 최종 축소된 이미지 픽셀 값:
[[ 93 170]
 [ 97  36]]


In [ ]:
import numpy as np

a = np.arange(12).reshape(3,4)
print(a)

b = a[ :, :, None ]
print(b.shape)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4, 1)
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]
