In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

In [7]:
data = load_breast_cancer()
print(type(data))
print(dir(data))

<class 'sklearn.utils._bunch.Bunch'>
['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']


In [8]:
X = data.data
# print(X)
y = data.target
# print(y)

print(X.shape, y.shape)
print(len(y))

(569, 30) (569,)
569


In [9]:
# 데이터 분할(학습 80%, 테스트 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape, y_train.shape) # (455, 30) (455,)
print(X_test.shape, y_test.shape)   # (114, 30) (114,)

(455, 30) (455,)
(114, 30) (114,)


In [12]:
# 모델 학습(로지스틱 회귀 모델)
model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)

print("fit done")

print(dir(model))


fit done
['C', '__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__sklearn_clone__', '__sklearn_tags__', '__str__', '__subclasshook__', '__weakref__', '_doc_link_module', '_doc_link_template', '_doc_link_url_param_generator', '_get_class_level_metadata_request_values', '_get_doc_link', '_get_fitted_attr_html', '_get_metadata_request', '_get_param_names', '_get_params_html', '_html_repr', '_init_callback_context', '_parameter_constraints', '_predict_proba_lr', '_repr_html_', '_repr_html_inner', '_repr_mimebundle_', '_validate_params', 'class_weight', 'classes_', 'coef_', 'decision_function', 'densify', 'dual', 'fit', 'fit_intercept', 'get_metadata_routing', 'get_params', 'intercept_', 'interc

In [ ]:
# 예측 (클래스 예측 및 확률 예측)
y_pred = model.predict(X_test)
print(y_pred)
# print(y_test==y_pred)
print(pd.Series(y_test==y_pred).unique())
print(pd.Series(y_test==y_pred).value_counts())
# print("정확도:", accuracy_score(y_test, y_pred))

y_proba = model.predict_proba(X_test)
print(y_proba)

[1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 0 0]
[ True False]
True     109
False      5
Name: count, dtype: int64
정확도: 0.956140350877193
[[1.21582263e-01 8.78417737e-01]
 [9.99999970e-01 3.04735433e-08]
 [9.98400302e-01 1.59969809e-03]
 [1.22427397e-03 9.98775726e-01]
 [1.41393006e-04 9.99858607e-01]
 [1.00000000e+00 2.00253498e-10]
 [1.00000000e+00 6.15347950e-11]
 [9.80717932e-01 1.92820681e-02]
 [1.57350194e-02 9.84264981e-01]
 [5.68899656e-03 9.94311003e-01]
 [7.07296413e-02 9.29270359e-01]
 [9.99190553e-01 8.09446888e-04]
 [1.10921726e-02 9.88907827e-01]
 [8.23924259e-01 1.76075741e-01]
 [7.87429879e-04 9.99212570e-01]
 [9.98250317e-01 1.74968272e-03]
 [1.19614263e-03 9.98803857e-01]
 [1.20608626e-05 9.99987939e-01]
 [6.12678024e-07 9.99999387e-01]
 [9.99999278e-01 7.22142596e-07]
 [1.72221322e-01 8

In [23]:
# 출력 : 혼합행렬
cm = confusion_matrix(y_test, y_pred)
print(cm)
'''
[[39  4]
[ 1 70]]
'''



[[39  4]
 [ 1 70]]


'\n[[39  4]\n[ 1 70]]\n'

In [28]:
# 평가지표 계산
acc = accuracy_score(y_test, y_pred) # (정답, 예측)
prec = precision_score(y_test, y_pred) # (정답, 예측)
rec = recall_score(y_test, y_pred)   # (정답, 예측)
f1 = f1_score(y_test, y_pred)       
print("정확도:", acc)
print("정밀도:", prec)
print("재현율:", rec)
print("F1 점수:", f1)

정확도: 0.956140350877193
정밀도: 0.9459459459459459
재현율: 0.9859154929577465
F1 점수: 0.9655172413793104


# 데이터가 불균형일때 발생하는 문제

불균형한 이진 분류로 만들기 위해 숫자 '7'만 True 나머지 숫자는 False로 설정

- 마찬가지로 fit은 아무것도 하지 않음
- predict에서는 무조건 0을 반환함
- 모든 예측을 다 0으로 하는 것! (모두 7이 아닌 다른 숫자라고 예측)
- 당연히 모델로서 말이 안 되는데 이것의 정확도를 측정

In [31]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [ ]:
class MyFakeClassifier(BaseEstimator):
    def fit(self, X, y): # 훈련할 개수
        pass

    def predict(self, X):   # 예측할 개수
        return np.zeros((len(X), 1), dtype=bool)